### ISSUE TITLE
forgotten login after update 

### ISSUE THREAD

**Issue by she888** [EdgePlus-MIA/EdgyBot#291]
After the 4.29v update, I was logged out of my account and due to my phone breaking i lost my login info.  How would I go about changing my info?

**Comment by gsrhax** [comment]
Get a new account for free

**Comment by she888** [comment]
how would I create a new account for free?

**Comment by EdgePlus-MIA** [comment]
... just fill out an order on the site again, its not hard. its free giveaway week
