### ISSUE TITLE
In need of a refund, I use Time4Learning.

### ISSUE THREAD

**Issue by bklaire07** [EdgePlus-MIA/EdgyBot#296]
I paid to use the bot, but its not working and I think that's because I use Time4Learning. If I could please get my money back that would be appreciated, I barely know how to use  this website so I wasn't able to find the FAQ.

**Comment by jevxz** [comment]
you can get the bot back for free on the edgeplus website

**Comment by bklaire07** [comment]
i use time4learning so i cant use it at all bc on the faq it says not compatible

**Comment by EdgePlus-MIA** [comment]
yeah but how is this our fault? Read the disclaimer and description, user error isn't our fault and we don't do refunds.
