### ISSUE TITLE
No, you are using incorrect initials for ur account. Enter your Edgenuity initials, the same ones on the top right corner for Edgenuity when making an order.

### ISSUE THREAD

**Issue by AshleyJ24** [EdgePlus-MIA/EdgyBot#298]
No, you are using incorrect initials for ur account. Enter your Edgenuity initials, the same ones on the top right corner for Edgenuity when making an order.

_Originally posted by @EdgePlus-MIA in https://github.com/EdgePlus-MIA/EdgyBot/issues/293#issuecomment-1622788429_

**Comment by AshleyJ24** [comment]
I am using the initials AJ which is the correct initials.  User name is AzrielJ password is May#0986.  This is what I initially used, what I am trying today, and they are not working.  Do I need to create a new account for the bot?  I already paid 45 for this last week

**Comment by gsrhax** [comment]
Yes. Ur supposed to create a new account for free, why else do u think there's a free giveaway going on for the next week 🤦‍♂️

**Comment by AshleyJ24** [comment]
didn't see that.  My sincere apologies!!  Aloha
