### ISSUE TITLE
Bot not doing much of anything

### ISSUE THREAD

**Issue by AshleyJ24** [EdgePlus-MIA/EdgyBot#299]
It says the bot is working both on english 10 and also world history and culture:1500 to present.  
   The issue is, is that it isn't doing anything.  Not even auto advancing through the different frames.  
last week for the 10 mins I used it, it did a lot more than this?

**Comment by gsrhax** [comment]
It's cuz ur using it wrong...

**Comment by AshleyJ24** [comment]
Your customer service skills need some help.
