### ISSUE TITLE
I paid for my class but shows up as not part of payment plan

### ISSUE THREAD

**Issue by moonman212** [EdgePlus-MIA/EdgyBot#300]
so I already paid the base price before for the bot awhile back along with a my english 4 class and now im trying to activate the bot for a summer class I have but when I went through the edgeplus website to pay for another class It never asked which class and showed up as me owing $0 but i still sent $10 on cashapp/ my cashapp is ($blaze4dayz867)/ I also checked the edgeplus website and it said my payment was verified but I went to edgenuity and it said my summer class wasnt part of payment plan. Im not looking for a refund I just want the bot for my class I paid for. If anything the class is named under( CMS Summer 2023 English III CR)

**Comment by EdgePlus-MIA** [comment]
click alt r or opt r, reset bot, login again, pick new class
