### ISSUE TITLE
Edgeplus

### ISSUE THREAD

**Issue by pldnotyou** [EdgePlus-MIA/EdgyBot#302]
It keeps saying "Incorrect information. Account does not exist" when I know damn well my account exists because I was just using it yesterday and now it wont work so can you fix this or like help w my account or sum because i know i didnt forget it at all because all my passwords be the same thing.

**Comment by demarcisholt** [comment]
same with me

**Comment by pldnotyou** [comment]
they need to hurry up and fix this issue bro

**Comment by gsrhax** [comment]
Contact 9296642543
