### ISSUE TITLE
My account exists already.

### ISSUE THREAD

**Issue by FlashFyreSS** [EdgePlus-MIA/EdgyBot#305]
Its trying to make me buy edgybot base price again after i already used it and just wanted to add classes. Any help?

**Comment by gsrhax** [comment]
Contact 9296642543

**Comment by RyMariee** [comment]
i contacted the # Nobody is answering .

**Comment by RyMariee** [comment]
it made me pay base price again and again but now it wont let me log in let me know if anything updates
