### ISSUE TITLE
Bot doesnt like algebra

### ISSUE THREAD

**Issue by ChaoticCow** [EdgePlus-MIA/EdgyBot#307]
I have an algebra 2 class, and a lot of the times while autoing itll get stuck on a question and not move on. this happens with other classes but only like once or twice. With alg it does it every few questions.

**Comment by ChaoticCow** [comment]
![image](https://github.com/EdgePlus-MIA/EdgyBot/assets/128778180/afeeb05e-12e0-455e-a9a0-7e9f9af88036)
this is what i mean btw

**Comment by gsrhax** [comment]
This is a known thing. That's why when you put the number of classes you want, it says it's not good for math/foreign language classes 👎
