### ISSUE TITLE
HELP PLEASE ASAP

### ISSUE THREAD

**Issue by Barrett2805** [EdgePlus-MIA/EdgyBot#313]
I had gotten 3 classes for free during the free week and did 2 and a half classes, then went on vacation and came back to my edgybot saying "This class is not included in your payment" PLEASE HELP I HAVE 50% left and 3 DAYS. THANK YOU!!!!!
![df5f6dbd8df9c710b34893511f50825f](https://github.com/EdgePlus-MIA/EdgyBot/assets/141685434/96ca79bb-3c7d-4a15-be35-7a81af1bfdd0)
![fec10bd13ec37a6281febd45418080a0](https://github.com/EdgePlus-MIA/EdgyBot/assets/141685434/6780ed9d-9093-42b3-9465-5da01da42aca)

**Comment by Barrett2805** [comment]
UPDATE: bought another class for 10$ and 4 hours later still nothing

**Comment by gsrhax** [comment]
Issue has been resolved, if not (I'm pretty sure it has), contact 9296642543
