### ISSUE TITLE
Just not working

### ISSUE THREAD

**Issue by trishszn** [EdgePlus-MIA/EdgyBot#320]
It was working fine, and then i went to go on another class and it's like its not even there anymore. I checked tampermonkey and everything is on correctly ,, I shut down chrome and everything.

**Comment by AveryTeamW** [comment]
Think this is something going on with everyone. Not working for me either

**Comment by AveryTeamW** [comment]
Mine is working, is yours?

**Comment by trishszn** [comment]
yes now it is

**Comment by EdgePlus-MIA** [comment]
make a new account on our new site for free: https://edgeplusv2.web.app
