### ISSUE TITLE
Bot not working 

### ISSUE THREAD

**Issue by Lobbo1** [EdgePlus-MIA/EdgyBot#321]
Everything was working fine then out of no where after about an hour of use it just stopped and all the menus that were associated with the extension disappeared.

**Comment by AveryTeamW** [comment]
Same here

**Comment by AveryTeamW** [comment]
Mine is working, is yours?

**Comment by EdgePlus-MIA** [comment]
make a new account on our new site for free: https://edgeplusv2.web.app
