### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by AveryTeamW** [EdgePlus-MIA/EdgyBot#322]
I just bought this two hours ago and the bot just randomly stopped working? Out of nowhere? Tried different browsers, it's just not anywhere as if it isn't in existence anymore.

**Comment by Lobbo1** [comment]
apparently GitHub is just having an issue rn so it'll probably be back up in a bit.

**Comment by AveryTeamW** [comment]
Good to hear

**Comment by AveryTeamW** [comment]
working now.
