### ISSUE TITLE
Purchase issues

### ISSUE THREAD

**Issue by kajinator** [EdgePlus-MIA/EdgyBot#323]
I paid for 2 addition classes. I'm using Windows and tried to use Alt + R and it says i've only purchased one class even though I purchased 2 additional classes. Could I please get my 2 additional classes added?
![image](https://github.com/EdgePlus-MIA/EdgyBot/assets/105234609/37d5a1de-604d-4cca-b7ff-dbea8739d9d1)

**Comment by EdgePlus-MIA** [comment]
make a new account on our new site for free: https://edgeplusv2.web.app
