### ISSUE TITLE
update 5.01 glitched

### ISSUE THREAD

**Issue by gear075** [EdgePlus-MIA/EdgyBot#325]
its not working for me.

**Comment by CARLOS-1010** [comment]
me too

**Comment by FanaticSpy20338** [comment]
Not working at all. Did anyones school recently change the login for edgenuity but it goes to the same profile and classes? Wonder if that has anything to do with it

**Comment by EdgePlus-MIA** [comment]
try latest update v5.02.

Completely reinstall tampermonkey along with script.
