### ISSUE TITLE
No access

### ISSUE THREAD

**Issue by kajinator** [EdgePlus-MIA/EdgyBot#326]
I created a new account, don't have access. I already paid $30 for 3 classes on the old version and $30 for the bot itself but it's saying I need to buy something to complete my order and gain access.
![image](https://github.com/EdgePlus-MIA/EdgyBot/assets/105234609/23a8e99f-a9a1-4740-ae23-08bfab24a26e)

**Comment by EdgePlus-MIA** [comment]
its free just make the order

try latest update v5.02.

Completely reinstall tampermonkey along with script.
