### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by AlligatorApple** [EdgePlus-MIA/EdgyBot#329]
script is not working for me and I don't know how to fix it, can someone please help me?

**Comment by EdgePlus-MIA** [comment]
try latest update v5.02.

Completely reinstall tampermonkey along with script.

**Comment by AlligatorApple** [comment]
Its still not working for me

**Comment by jaxon1080** [comment]
me either, did you get yours fixed??

**Comment by AlligatorApple** [comment]
nope
