### ISSUE TITLE
Edgy bot paid for but no longer working

### ISSUE THREAD

**Issue by jaxon1080** [EdgePlus-MIA/EdgyBot#331]
I bought edgybot 3 days ago so I didn't use an email to sign up, I used my phone #. Its not loading or working, and I tried reinstalling tampermonkey but now it's like I have the userscript but its no longer working. I have assignments due soon and I cant even access my edgenuity rn help!!

**Comment by CARLOS-1010** [comment]
It's buggin for everyone, i made a new account on the new edgy bo,t reinstalled tampermonkey, and its still not popping up in edgenuity for me

**Comment by creepz818** [comment]
it is down host is working on it
