### ISSUE TITLE
New update problems

### ISSUE THREAD

**Issue by Kemhiru** [EdgePlus-MIA/EdgyBot#332]
So after this new update the bot broke entirely, the menu doesn't even pop up anymore. I tried re-installing but the latest update link still takes me to 5.01. I'm also having some trouble getting into the website as I signed up with my number but the login INSISTS on me using an email, so I guess I'm just locked out of that. I'm begging on my knees pleading for a fix or just for someone to show me what I'm doing wrong because I have a few classes to catch up on today.

**Comment by jaxon1080** [comment]
Hey exact same thing happened to me, you have to create a new account and purchase it again through square, but its totally free so just go to the square checkout after you make a new account and that should work. I got edgybot to load but now its just not functional
