### ISSUE TITLE
Login issues

### ISSUE THREAD

**Issue by kajinator** [EdgePlus-MIA/EdgyBot#333]
I'm logged in on version 5.07 but it's not recognizing it.
![image](https://github.com/EdgePlus-MIA/EdgyBot/assets/105234609/8c162183-7f44-4c85-8b6f-9b0bade54ffc)

**Comment by EdgePlus-MIA** [comment]
should all be fixed now, latest version: v5.13
Please uninstall tampermonkey and reinstall EdgyBot from : https://edgeplusv2.web.app

Check out our discord for immediate support by EdgePlus team and other EdgePlus customers/users: https://discord.gg/AhMvKX2qYY
