### ISSUE TITLE
bot wont update to 5

### ISSUE THREAD

**Issue by ramirez250** [EdgePlus-MIA/EdgyBot#335]

**Comment by saigeman1117** [comment]
I am having the same issue with it not updating to v5.02. I click the link and nothing happens

**Comment by iTrap9s** [comment]
same problem

**Comment by ramirez250** [comment]
these needs to get resolved lol someone contact the maker please I cant

**Comment by AlligatorApple** [comment]
I've been trying to resolve mine for 3 days and no help, he told me to uninstall and reinstall but that did not work and he hasn't replied, honestly this seems like a waste of money.

**Comment by AlligatorApple** [comment]
He updated it you have to go into his profile and click on the link he has pinned on his bio that will take you to the website where u can update the script.

**Comment by hazelnutboy123** [comment]
bro since it aint free and its for students this is bs
